api = "0.9"

[buildpack]

id = "anasinnyk/dotenv"
version = "0.0.3"
name = "dotenv"
homepage = "https://github.com/anasinnyk/dotent-buildpack"
description = "Load environment variables form .env file"
keywords = ["dotenv"]

  [[buildpack.licenses]]

  type = "MIT"
  uri = "https://github.com/anasinnyk/dotenv-buildpack/blob/master/LICENSE"

[[stacks]]

id = "*"
